data:
  dataRetention: forever
  dataRetentionValue: null
  fileUploadsAction: retain
  notifications:
    -
      attachAssets: null
      attachFiles: true
      attachPdf: null
      bcc: null
      cc: null
      conditions:
        conditionRule: all
        sendRule: send
      content: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
      enableConditions: false
      enabled: true
      from: '{systemEmail}'
      fromName: '{systemName}'
      handle: adminNotification
      name: 'Admin notification'
      pdfTemplateId: null
      recipients: email
      replyTo: null
      replyToName: '{field:email}'
      sender: null
      subject: '[{formName}] {field:email}'
      templateId: 1
      to: '{systemEmail}'
      toConditions: null
    -
      attachAssets: null
      attachFiles: true
      attachPdf: null
      bcc: null
      cc: null
      conditions: null
      content: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Wij nemen zo snel mogelijk contact met je op."}]}]'
      enableConditions: false
      enabled: true
      from: '{systemEmail}'
      fromName: '{systemName}'
      handle: userNotification
      name: 'User notification'
      pdfTemplateId: null
      recipients: email
      replyTo: null
      replyToName: null
      sender: null
      subject: '{field:firstName}, bedankt voor je intresse'
      templateId: 2
      to: '{field:email}'
      toConditions: null
  pages:
    -
      label: 'Page 1'
      rows:
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cookieName: null
                cssClasses: null
                defaultOption: custom
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: hiddenPageTitle
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: 'Pagina titel'
                labelPosition: verbb\formie\positions\Hidden
                matchField: null
                placeholder: null
                prePopulate: null
                queryParameter: null
                required: false
                visibility: null
              type: verbb\formie\fields\Hidden
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cookieName: null
                cssClasses: null
                defaultOption: custom
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: hiddenPageUrl
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: 'Pagina URL'
                labelPosition: verbb\formie\positions\Hidden
                matchField: null
                placeholder: null
                prePopulate: null
                queryParameter: null
                required: false
                visibility: null
              type: verbb\formie\fields\Hidden
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: name
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Naam
                labelPosition: null
                limit: false
                matchField: null
                max: null
                maxType: characters
                min: null
                minType: characters
                placeholder: null
                prePopulate: null
                required: false
                uniqueValue: false
                visibility: null
              type: verbb\formie\fields\SingleLineText
            -
              settings:
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: firstName
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Voornaam
                labelPosition: null
                limit: false
                matchField: null
                max: null
                maxType: characters
                min: null
                minType: characters
                placeholder: null
                prePopulate: null
                required: false
                uniqueValue: false
                visibility: null
              type: verbb\formie\fields\SingleLineText
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                countryDefaultValue: null
                countryEnabled: false
                countryLanguage: auto
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: phone
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Telefoon
                labelPosition: null
                matchField: null
                placeholder: null
                prePopulate: null
                required: false
                visibility: null
              type: verbb\formie\fields\Phone
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: email
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Email
                labelPosition: null
                matchField: null
                placeholder: null
                prePopulate: null
                required: false
                uniqueValue: false
                validateDomain: false
                visibility: null
              type: verbb\formie\fields\Email
        -
          fields:
            -
              settings:
                allowMultipleSources: false
                allowedKinds:
                  - image
                  - pdf
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                displayType: dropdown
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                filenameFormat: null
                handle: fileUpload
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: 'File upload'
                labelPosition: null
                labelSource: title
                layout: vertical
                limitFiles: null
                limitOptions: null
                matchField: null
                multi: false
                orderBy: 'title ASC'
                placeholder: null
                prePopulate: null
                required: false
                restrictFiles: true
                sizeLimit: null
                sizeMinLimit: null
                source: null
                sourceType: groups
                sources: '*'
                uploadLocationSource: null
                uploadLocationSubpath: null
                visibility: null
              type: verbb\formie\fields\FileUpload
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: dropdown
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Dropdown
                labelPosition: null
                layout: null
                limitOptions: false
                matchField: null
                max: null
                min: null
                multi: false
                optgroups: true
                options:
                  -
                    isDefault: true
                    label: 'Option 1'
                    value: ''
                  -
                    isDefault: false
                    label: 'Option 2'
                    value: 'Option 2'
                  -
                    isDefault: false
                    label: 'Option 3'
                    value: 'Option 3'
                placeholder: null
                prePopulate: null
                required: false
                visibility: null
              type: verbb\formie\fields\Dropdown
        -
          fields:
            -
              settings:
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: null
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: message
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: Bericht
                labelPosition: null
                limit: false
                matchField: null
                max: null
                maxType: characters
                min: null
                minType: characters
                placeholder: null
                prePopulate: null
                required: false
                richTextButtons:
                  - bold
                  - italic
                uniqueValue: false
                useRichText: false
                visibility: null
              type: verbb\formie\fields\MultiLineText
        -
          fields:
            -
              settings:
                checkedValue: 'Yes'
                conditions: null
                containerAttributes: null
                cssClasses: null
                defaultValue: false
                description:
                  -
                    attrs:
                      textAlign: start
                    content:
                      -
                        text: 'Ik ga akkoord met de privacy policy'
                        type: text
                    type: paragraph
                emailValue: null
                enableConditions: false
                enableContentEncryption: false
                enabled: true
                errorMessage: null
                handle: privacyPolicy
                includeInEmail: true
                inputAttributes: null
                instructions: null
                instructionsPosition: null
                label: 'Privacy policy'
                labelPosition: verbb\formie\positions\Hidden
                matchField: null
                placeholder: null
                prePopulate: null
                required: false
                uncheckedValue: 'No'
                visibility: null
              type: verbb\formie\fields\Agree
      settings:
        backButtonLabel: Back
        buttonsPosition: left
        containerAttributes: null
        cssClasses: null
        enableJsEvents: false
        enableNextButtonConditions: false
        enablePageConditions: false
        inputAttributes: null
        saveButtonLabel: Save
        saveButtonStyle: link
        showBackButton: false
        showSaveButton: false
        submitButtonLabel: Submit
  settings:
    collectIp: false
    collectUser: false
    dataRetention: null
    dataRetentionValue: null
    defaultEmailTemplateId: '2'
    defaultInstructionsPosition: verbb\formie\positions\AboveInput
    defaultLabelPosition: verbb\formie\positions\AboveInput
    disableCaptchas: false
    displayCurrentPageTitle: false
    displayFormTitle: false
    displayPageProgress: false
    displayPageTabs: false
    errorMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Kan formulier niet opslaan vanwege fouten."}]}]'
    errorMessagePosition: top-form
    fileUploadsAction: null
    integrations:
      duplicate:
        enabled: '1'
        showAllPages: ''
      honeypot:
        enabled: '1'
        showAllPages: ''
      javascript:
        enabled: '1'
        showAllPages: ''
    limitSubmissions: null
    limitSubmissionsIpAddressMessage: null
    limitSubmissionsIpAddressNumber: null
    limitSubmissionsIpAddressType: null
    limitSubmissionsMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    limitSubmissionsNumber: null
    limitSubmissionsType: total
    loadingIndicator: spinner
    loadingIndicatorText: null
    pageRedirectUrl: null
    progressPosition: end
    progressValuePosition: inside-center
    redirectUrl: null
    requireUser: false
    requireUserMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    requiredIndicator: asterisk
    scheduleForm: false
    scheduleFormEnd: null
    scheduleFormExpiredMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormPendingMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"}}]'
    scheduleFormStart: null
    scrollToTop: true
    submissionTitleFormat: '[{formName}] {field:email}'
    submitAction: message
    submitActionFormHide: true
    submitActionMessage: '[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Inzending opgeslagen."}]}]'
    submitActionMessagePosition: top-form
    submitActionMessageTimeout: null
    submitActionTab: null
    submitActionUrl: null
    submitMethod: ajax
    validationOnFocus: false
    validationOnSubmit: true
  userDeletedAction: retain
defaultStatus: 902b7939-e38e-41a1-b8ee-0daaa5882508 # New
handle: defaultStencil
name: 'Default stencil'
submitActionEntry: null
template: 8f5be8c6-8638-440c-9100-d3ac0e8547e1 # Default template
