allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  96eeba57-c639-4b1f-824f-3e28054e3def:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ea5c931e-5fd1-474a-a7f2-6e921db4bee4 # Driver Code
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f93367c9-c325-4d9b-8ae4-87b3f6081ca2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c20bf6d0-eda3-4415-a90b-44eaee61232e # Driver ID
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4acf4ec2-5cb7-4910-8d1c-cfd189f8921f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 79658790-f071-4e99-97d1-0b036e5bfae2 # Driver First Name
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a8e44a1-9f44-4425-a39f-deb174af03ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1508b9fa-ab88-4b8e-aacf-da477536075f # Driver Last Name
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a34db0bd-0622-45eb-a91b-3f89bd59ad38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 78e9870e-196b-495f-bb5e-eb1d8865954d # Team Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3900112b-03e2-4f02-a117-e77d0e021895
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 75fb5ded-fb3d-4f10-853c-b3c065fb37b1 # Is Active
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c92be12-4fa3-4c67-8633-1b8c2c6e4156
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-04T09:28:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0e06e559-f9be-4000-930b-f7096c319a95 # Driver Photo
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e14b20b8-af95-4680-bd05-684d44568f83
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3955b2cc-8ed1-4c4c-ab76-333f40fdc534
        userCondition: null
    thumbFieldKey: null
handle: entryDrivers
hasTitleField: false
icon: null
name: Drivers
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{driverFirstName} {driverLastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
