columnSuffix: null
handle: fieldForm
instructions: null
name: Formulier
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Kies een formulier'
  showSearchInput: true
  showSiteMenu: true
  sources:
    - 'template:8f5be8c6-8638-440c-9100-d3ac0e8547e1' # Default template
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
