columnSuffix: lyhybctx
handle: isActive
instructions: 'Is driver active this season?'
name: 'Is Active'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
