columnSuffix: verttqsd
handle: pointsEarned
instructions: 'Points earned from this prediction'
name: 'Points Earned'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
