columnSuffix: null
contentColumnType: string
handle: predictionPlayer
instructions: 'Player who made this prediction'
name: 'Prediction Player'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
