columnSuffix: wychwbrz
handle: raceRound
instructions: 'Round number in the season'
name: 'Race Round'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
