columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
  sitemapTabEnabled: '1'
  twitterEnabledFields:
    - seoPreview
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: site
type: nystudio107\seomatic\fields\SeoSettings
