columnSuffix: colfcgsh
contentColumnType: text
handle: teamName
instructions: 'Current team'
name: 'Team Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
