dateModified: 1772644863
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: 'F1 GOOAT'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Channels
      key: 'heading:3aa5503a-0a5b-4e04-8695-c516d65ed46e'
      page: 'F1 GOOAT'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:faabdab7-b665-4a65-b0b7-03dc902e6851' # Drivers
      page: 'F1 GOOAT'
      tableAttributes:
        - 'field:79658790-f071-4e99-97d1-0b036e5bfae2' # Driver First Name
        - 'field:c20bf6d0-eda3-4415-a90b-44eaee61232e' # Driver ID
        - 'field:1508b9fa-ab88-4b8e-aacf-da477536075f' # Driver Last Name
        - 'field:78e9870e-196b-495f-bb5e-eb1d8865954d' # Team Name
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:40f3c457-bc98-479b-bc8f-4112d9d1cb55' # Players
      page: 'F1 GOOAT'
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:c35d0db6-ae05-43c9-8bdb-c92696a228e5' # Predictions
      page: 'F1 GOOAT'
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:b0c75c6b-ebdc-4798-af15-4441983df8e9' # Races
      page: 'F1 GOOAT'
      tableAttributes:
        - 'field:daa79e49-c575-4c86-abb5-bef8fd86876a' # Race Round
        - 'field:cf0b87ab-e617-4f90-92cc-440a6aa36912' # Race Status
        - 'field:f026cf70-26cc-4731-a17f-b16713fb81c1' # Race Date
        - 'field:f125241f-f44f-4e39-b357-76186e36cd32' # Season
      type: native
elementSourcesPages:
  craft\elements\Entry:
    'F1 GOOAT':
      icon: car
email:
  fromEmail: $FROM_EMAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_EMAIL
  template: null
  transportSettings:
    apiKey: $MAILGUN_API
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  files:
    hasUrls: true
    name: Bestanden
    settings:
      path: '@webroot/uploads/files'
    type: craft\fs\Local
    url: '@web/uploads/files'
  icons:
    hasUrls: true
    name: Iconen
    settings:
      path: '@webroot/uploads/icons'
    type: craft\fs\Local
    url: '@web/uploads/icons'
meta:
  __names__:
    0e06e559-f9be-4000-930b-f7096c319a95: 'Driver Photo' # Driver Photo
    01b9fa51-7c82-495d-a125-54246848dda3: 'Multiple line plain text' # Multiple line plain text
    1e26dc00-d92d-49f6-a155-a75a8944b681: Tekst # Tekst
    4a511286-2b52-4efb-baf0-fd1e1923c6f1: Video # Video
    4c8aa25e-d55d-4719-bac5-472d04d624d2: Afbeeldingen # Afbeeldingen
    4ebfb8a1-8dc0-4bad-8876-a2fbce75f84c: 'Prediction Player' # Prediction Player
    6a480a33-0e75-411d-8738-15d2eb5d009e: Drivers # Drivers
    7cae5a52-6822-46d5-97f3-2437b11310a0: 'Plain text' # Plain text
    7e74b128-601c-4dc0-ad90-cffba00195a4: 'Total Points' # Total Points
    039ea3d5-d4e4-4e88-bd0c-5a3746c3918f: 'Previous Standing' # Previous Standing
    40f3c457-bc98-479b-bc8f-4112d9d1cb55: Players # Players
    43b3cc3e-6293-45a4-9321-2c0bd1d82aa6: 'Current Standing' # Current Standing
    60f45fd4-6f69-41ab-a119-f016b485a9a5: $SITE_NAME # $SITE_NAME
    63c31cd7-9c31-469c-93fd-c5e8c173695f: 'Points Earned' # Points Earned
    70c7bc84-96ad-46cb-a4fa-cb199f539360: 'Player Email' # Player Email
    71e989b9-a8bf-4d15-b898-513b8d37723d: 'Titel bold' # Titel bold
    74ff37ae-4ee1-4676-8e95-b511d6b2eb2f: '2025' # 2025
    75fb5ded-fb3d-4f10-853c-b3c065fb37b1: 'Is Active' # Is Active
    78e9870e-196b-495f-bb5e-eb1d8865954d: 'Team Name' # Team Name
    0231b113-9a76-492f-b534-9bf406cf2a20: 'Selection Order' # Selection Order
    284e462f-58a4-4a36-9184-3e98ac33a54d: Titel # Titel
    659be255-b4f4-42bc-a89b-af374fb891e7: Homepage # Homepage
    668cec72-2c2b-407b-a3be-99e1205fc262: Predictions # Predictions
    765f1d3e-7083-49ca-8baa-d90996d0366f: 'Driver Name' # Driver Name
    1508b9fa-ab88-4b8e-aacf-da477536075f: 'Driver Last Name' # Driver Last Name
    1541ac85-c9a2-49ea-8b52-7e77f28e0a02: Players # Players
    3191a900-122a-4c10-84c3-2004466abd96: 'Social Media - Type' # Social Media - Type
    4482efdb-66c1-454c-a53c-eec4185542c6: Races # Races
    8191b742-84f0-4c30-bc48-30474a878186: 'Actual Position' # Actual Position
    24212549-c5b0-4e88-9184-f43bb909aefe: Afbeelding # Afbeelding
    37578336-98ad-4efc-9e87-ab127f7ac8d3: 'Race Results' # Race Results
    79658790-f071-4e99-97d1-0b036e5bfae2: 'Driver First Name' # Driver First Name
    a6bbbfb4-c43f-47a9-b53d-5a01e2c3d166: 'Prediction Race' # Prediction Race
    a88d754d-03b9-4e5a-9984-de49f12d0629: '2026' # 2026
    aab1e909-1491-4d02-934a-4a03b4f3b858: 'Public Schema' # Public Schema
    b0c75c6b-ebdc-4798-af15-4441983df8e9: Races # Races
    c20bf6d0-eda3-4415-a90b-44eaee61232e: 'Driver ID' # Driver ID
    c35d0db6-ae05-43c9-8bdb-c92696a228e5: Predictions # Predictions
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    ce448a77-a759-4cb5-b72a-03b3e0267abc: Toggle # Toggle
    cf0b87ab-e617-4f90-92cc-440a6aa36912: 'Race Status' # Race Status
    daa79e49-c575-4c86-abb5-bef8fd86876a: 'Race Round' # Race Round
    ddae94aa-4ca8-4566-a31f-fdc6a0042bc1: Intro # Intro
    e80a0524-bdff-4f2f-a981-38ae6ce47f2d: Iconen # Iconen
    ea5c931e-5fd1-474a-a7f2-6e921db4bee4: 'Driver Code' # Driver Code
    f026cf70-26cc-4731-a17f-b16713fb81c1: 'Race Date' # Race Date
    f521d366-2967-4c06-9054-55ba57b7a2c0: Bestanden # Bestanden
    f125241f-f44f-4e39-b357-76186e36cd32: Season # Season
    faabdab7-b665-4a65-b0b7-03dc902e6851: Drivers # Drivers
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  control-panel-element-counter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: Europe/Brussels
