dateModified: 1772615452
email:
  fromEmail: $FROM_EMAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_EMAIL
  template: null
  transportSettings:
    apiKey: $MAILGUN_API
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  files:
    hasUrls: true
    name: Bestanden
    settings:
      path: '@webroot/uploads/files'
    type: craft\fs\Local
    url: '@web/uploads/files'
  icons:
    hasUrls: true
    name: Iconen
    settings:
      path: '@webroot/uploads/icons'
    type: craft\fs\Local
    url: '@web/uploads/icons'
meta:
  __names__:
    01b9fa51-7c82-495d-a125-54246848dda3: 'Multiple line plain text' # Multiple line plain text
    1e26dc00-d92d-49f6-a155-a75a8944b681: Tekst # Tekst
    4a511286-2b52-4efb-baf0-fd1e1923c6f1: Video # Video
    4c8aa25e-d55d-4719-bac5-472d04d624d2: Afbeeldingen # Afbeeldingen
    6adc95df-cd57-491f-bc86-0dd624a0834f: Header # Header
    7b415d86-6971-42e8-95f9-85c38e9748b2: Footer # Footer
    7cae5a52-6822-46d5-97f3-2437b11310a0: 'Plain text' # Plain text
    60f45fd4-6f69-41ab-a119-f016b485a9a5: $SITE_NAME # $SITE_NAME
    71e989b9-a8bf-4d15-b898-513b8d37723d: 'Titel bold' # Titel bold
    97a73885-23dc-4d93-afb3-d8dcfbc3a7ae: Algemeen # Algemeen
    284e462f-58a4-4a36-9184-3e98ac33a54d: Titel # Titel
    659be255-b4f4-42bc-a89b-af374fb891e7: Homepage # Homepage
    3191a900-122a-4c10-84c3-2004466abd96: 'Social Media - Type' # Social Media - Type
    24212549-c5b0-4e88-9184-f43bb909aefe: Afbeelding # Afbeelding
    a88d754d-03b9-4e5a-9984-de49f12d0629: '2026' # 2026
    aab1e909-1491-4d02-934a-4a03b4f3b858: 'Public Schema' # Public Schema
    c4a6f1d0-769c-457a-9458-65910758520d: Homepage # Homepage
    c55ca0a9-4bd6-409b-afd8-c1884dafecd0: Team # Team
    ce448a77-a759-4cb5-b72a-03b3e0267abc: Toggle # Toggle
    ddae94aa-4ca8-4566-a31f-fdc6a0042bc1: Intro # Intro
    e80a0524-bdff-4f2f-a981-38ae6ce47f2d: Iconen # Iconen
    f521d366-2967-4c06-9054-55ba57b7a2c0: Bestanden # Bestanden
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  control-panel-element-counter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: Europe/Brussels
