defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6a480a33-0e75-411d-8738-15d2eb5d009e # Drivers
handle: drivers
maxAuthors: 1
name: Drivers
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: none
siteSettings:
  74ff37ae-4ee1-4676-8e95-b511d6b2eb2f: # Season 2025
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  a88d754d-03b9-4e5a-9984-de49f12d0629: # Season 2026
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
