handle: formieDefault
name: 'Default template'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: 1
template: _formie/formieDefault
useCustomTemplates: true
